### ISSUE TITLE
Feature Request: More convenience around the connection URI

### ISSUE THREAD

**Issue by ursi** [Quelklef/local-postgres#4]
The connection URI is going to be needed in nearly every use case of this library, and this is the the best way to do it afaik.

```bash
export DB_CONSTR=$(lpg cmd .database bash -c 'echo $LPG_CONNSTR')
```

And this only works if you want the one database in your cluster. If you want to use another database, you have to look at the source code to figure out the following.

```bash
export LPG_LOC=$(lpg cmd .database bash -c 'echo $LPG_LOC')
export OTHER_DB="postgresql://postgres@localhost/other-db?host=$LPG_LOC/socket"
```

I would love a nice command that covers these use cases.

**Comment by Quelklef** [comment]
First thought: I can add `lpg connstr <loc>` as an alias for `lpg bash <loc> 'echo $LPG_CONNSTR'`, easy enough

Want to think more about multiple databases though

**Comment by Quelklef** [comment]
Side-note, but what do you think of changing `lpg cmd <loc> <cmd>` to `lpg do <loc> cmd <cmd>` and `lpg bash <loc> <cmd>` to `lpg do <loc> bash <cmd>`, etc, etc?

More uniform and allows for one to do `alias my-lpg='lpg do ./my-instance-log '` as a way to create a "closure" that knows your specific LPG location

**Comment by Quelklef** [comment]
None of the other commands would need to be changed, right? Just the hypothetical `lpg connstr`. And `lpg psql`, if that were to be added

**Comment by Quelklef** [comment]
1. Re connection strings: how about `lpg connstr <loc>`? Can also add `lpg psql <loc>`, since `psql` is a pretty common operation and writing `lpg cmd <loc> psql` is vaguely annoying

2. Re databases: to support multiple databases, only `lpg connstr` would need to be changed, right? I could add a `-d <db-name>` flag. Could add one to `lpg psql`, too, for convenience

    It could also be nice to have `-d` on `lpg make`, but I'm not sure. Since `lpg make` is just a wrapper around `initdb`, my hope was that `initdb` would have some kind of `-d` flag, but [it doesn't](https://stackoverflow.com/a/72515015).

**Comment by ursi** [comment]
if `lpg connstr` took an optional database argument, that would cover my use case.
```
lpg connstr LOC [DATABASE]
```

**Comment by Quelklef** [comment]
right. Is that different from my `-d` proposal?

**Comment by ursi** [comment]
Not really, I just managed to not remember that from my first read, and not include it in my second lol. 

So my question there is, is `-d` being used to leave space for more arguments in the future?

**Comment by Quelklef** [comment]
Yeah, and for readability

**Comment by Quelklef** [comment]
we now have `lpg on <lpg-loc> get-connstr [ -d <db-name> ]`; sufficient to close this issue?

**Comment by ursi** [comment]
yes

**Comment by Quelklef** [comment]
slayy

**Comment by Quelklef** [comment]
please give this repo and my account a five-star review on yelp 🙏
